language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  - "pypy"
install:
  - pip install tox-travis
  - pip install "virtualenv<14.0.0"
  - pip install -U setuptools
  - pip install -U
  - pip install -U pytest
  - pip install -U pytest-mock
  - pip install -e .
  - pip list
script:
  - tox
notifications:
  email: false