language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  - "pypy"
install:
  - pip install tox-travis
  - pip install "virtualenv<14.0.0"
  - pip install -U pytest
  - pip install -U pytest-mock
script:
  - tox
after_success:
  - coveralls
notifications:
  email: false